In [1]:
# Q1. What are the benefits of the built-in array package, if any?
# ANS-->
# The Array is built-in Python, which only means that you don’t need to download and install it because it comes with native Python for sure.
# However, just like the other built-in libraries such as “datetime”, you still need to import it.

In [2]:
# Q2. What are some of the array package's limitations?
# ANS-->
# An array which is formed will be homogeneous. 
# That is, in an integer array only integer values can be stored, while in a float array only floating value and character array can have only characters.
# Thus, no array can have values of two data types.

In [3]:
# Q3. Describe the main differences between the array and numpy packages.
# ANS-->
# An array consumes less memory and is convenient to use. 
# NumPy uses much less memory to store data and it provides a mechanism of specifying the data types.

In [4]:
# Q4. Explain the distinctions between the empty, ones, and zeros functions.
# ANS-->
# empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster.
# On the other hand, it requires the user to manually set all the values in the array, and should be used with caution. Return a new array setting values to zero.


In [6]:
# Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable
# argument?
# ANS-->
# The function is called with N parameters, where N is the rank of shape. 
# Each parameter represents the coordinates of the array varying along a specific axis.
# numpy.fromfunction() function construct an array by executing a function over each coordinate and the resulting array, 
# therefore, has a value fn(x, y, z) at coordinate (x, y, z).

import numpy as np

sos=np.fromfunction(lambda i, j: i*j, (4, 4), dtype = float)

print(sos)

[[0. 0. 0. 0.]
 [0. 1. 2. 3.]
 [0. 2. 4. 6.]
 [0. 3. 6. 9.]]


In [7]:
# Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as
# an int or a floating-point value) through addition, as in the expression A + n?
# ANS-->
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [8]:
# Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)?
# What is the outcome?
# ANS-->
# Probably the most important array operator is the · If a scalar value is assigned to an array variable,
# the scalar value becomes the single element of an array:

In [9]:
# Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to
# one of these arrays?
# ANS-->
# The dtype of any numpy array containing string values is the maximum length of any string present in the array. Once set, 
# it will only be able to store new string having length not more than the maximum length at the time of the creation.

In [17]:
# Q9. What happens when you combine two numpy arrays using an operation like addition (+) or
# multiplication (*)? What are the conditions for combining two numpy arrays?
# ANS-->
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)


print("***"*20)



A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))

print("Adding to arrays: ")
print(A + B)

print("\nMultiplying two arrays: ")
print(A * (B + 1))

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
************************************************************
Adding to arrays: 
[[12. 13. 14.]
 [22. 23. 24.]
 [32. 33. 34.]]

Multiplying two arrays: 
[[22. 24. 26.]
 [42. 44. 46.]
 [62. 64. 66.]]


In [18]:
# Q10. What is the best way to use a Boolean array to mask another array?
# ANS-->
# To create a boolean mask from an array, use the ma.make_mask() method in Python Numpy. The function can accept any sequence that is convertible to integers, or nomask. 
# Does not require that contents must be 0s and 1s, values of 0 are interpreted as False, everything else as True.


import numpy as np
import numpy.ma as ma

# Create an array with zeros using the numpy.zeros() method in Python Numpy
arr = np.zeros(7)
print("Array...", arr)

# To Create a boolean mask from an array, use the ma.mask_mask() method in Python Numpy
print("Masked Array...", ma.make_mask(arr))
# Type of Array
print("Array type...", arr.dtype)

# Get the dimensions of the Array
print("Array Dimensions...",arr.ndim)

# Get the shape of the Array
print("Our Array Shape...",arr.shape)

# Get the number of elements of the Array
print("Elements in the Array...",arr.size)

Array... [0. 0. 0. 0. 0. 0. 0.]
Masked Array... False
Array type... float64
Array Dimensions... 1
Our Array Shape... (7,)
Elements in the Array... 7


In [20]:
# Q11. What are three different ways to get the standard deviation of a wide collection of data using
# both standard Python and its packages? Sort the three of them by how quickly they execute.
# ANS-->
# Standard deviation is about determining or measuring the spread of a given data set (sample or population)
# While calculating standard deviation of a sample of data, Bessel’s correction is applied (usage of N-1 instead of N) for calculating the average of squared difference of data points from its mean.
# You can calculate the standard deviation of population and sample using pstdev() and stdev() methods rspectively of statistics library
# You can calculate the standard deviation using std() method of Numpy library. For calculating standard deviation of sample of data, the value of ddof parameter is passed as 1.
# Use the standard deviation formula for sample when data size is small else use standard deviation formula for population.


from statistics import mean
arr1 = [10, 16, 8, 22]
 
arr2 = [12, 18, 12, 14]
# Calculate mean
#
mean(arr1), mean(arr2)
#
# Custom code in Python for calculating the mean
#
def mean(arr):
    sum = 0;
    for i in range(len(arr)):
        sum += arr[i]
    return sum / len(arr)

In [21]:
import math
'''
Calculate the biased and unbiased estimation of
standard deviation
'''
def stddev(arr, dist='sample'):
    squaredSum = 0.0
    meanArr = mean(arr)
    for i in range(len(arr)):
        squaredSum += math.pow((arr[i] - meanArr),2)
        i += 1
    sdVal = 0
    if dist == 'sample':
        #
        # For biased estimation, the formula becomes
        # SQRT(((Xi - Xmean)**2)/N)
        #
        sdVal = math.sqrt(squaredSum/(len(arr) - 1))
    elif dist == 'population':
        #
        # For unbiased estimation, the formula becomes
        # SQRT(((Xi - Xmean)**2)/(N-1))
        #
        sdVal = math.sqrt(squaredSum/(len(arr)))
    else:
        return -1
    return sdVal
 
stddev(arr1), stddev(arr2)

(6.324555320336759, 2.8284271247461903)

In [24]:
# 12. What is the dimensionality of a Boolean mask-generated array?
# ANS-->
# What is returned is a one-dimensional array filled with all the values that meet this condition; 
# in other words, all the values in positions at which the mask array is True .
